plugins { id 'com.android.application' }

android { namespace 'com.shreebalaji.scriptingacademy'; compileSdk 35
    defaultConfig { applicationId 'com.shreebalaji.scriptingacademy'; minSdk 23; targetSdk 35; versionCode 5; versionName '5.0' }
}


dependencies { implementation 'androidx.webkit:webkit:1.17.1' }
